name: build-dev
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          sudo apt install sshpass

      - name: Stop and Remove Previous
        working-directory: ./
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          echo "Running commands on VPS"
          cd ~/sites/ani-pwa-dev
          pm2 stop ani-pwa-dev
          cd ~/sites
          rimraf ~/sites/ani-pwa-dev
          EOF

      - name: Build and Start New
        working-directory: ./
        env:
          NODE_ENV: development
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          BOOKS_API_KEY: ${{ secrets.BOOKS_API_KEY }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          STRIPE_API_TOKEN: ${{ secrets.STRIPE_API_TOKEN }}
          PUBLIC_STRIPE_KEY_LIVE: ${{ secrets.PUBLIC_STRIPE_KEY_LIVE }}
          PUBLIC_STRIPE_KEY_TEST: ${{ secrets.PUBLIC_STRIPE_KEY_TEST }}
          STRIPE_SECRET_KEY_LIVE: ${{ secrets.STRIPE_SECRET_KEY_LIVE }}
          STRIPE_SECRET_KEY_TEST: ${{ secrets.STRIPE_SECRET_KEY_TEST }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          echo "Running commands on VPS"
          cd ~/sites
          git clone git@github.com:hasanirogers/ani-pwa.git ani-pwa-dev --branch develop
          cd ~/sites/ani-pwa-dev
          cat > .env <<EOL
          NODE_ENV=development
          MAIL_HOST=$MAIL_HOST
          MAIL_USER=$MAIL_USER
          MAIL_PASS=$MAIL_PASS
          PUBLIC_RUNTIME_ENVIRONMENT=development
          BOOKS_API_KEY=$BOOKS_API_KEY
          SUPABASE_DB_PASSWORD=$SUPABASE_DB_PASSWORD
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
          STRIPE_API_TOKEN=$STRIPE_API_TOKEN
          PUBLIC_STRIPE_KEY_LIVE=$PUBLIC_STRIPE_KEY_LIVE
          PUBLIC_STRIPE_KEY_TEST=$PUBLIC_STRIPE_KEY_TEST
          STRIPE_SECRET_KEY_LIVE=$STRIPE_SECRET_KEY_LIVE
          STRIPE_SECRET_KEY_TEST=$STRIPE_SECRET_KEY_TEST
          STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
          EOL
          npm install
          npm run build
          pm2 start "npm run serve" --name "ani-pwa-dev"
          EOF
